### PR TITLE
Adding to adversarial attacks

### PR DESCRIPTION
**Pull request by hwarden162**
Adding a section on adversarial attacks in tumour classification. Links back to previous sessions on image based machine learning and saliency maps and links adversarial attacks in with discussions had earlier in this lesson on whether machine learning should be used for "important" tasks such as medical diagnosis.

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks Hugh! In this example, is there a clear reason why someone would want to manipulate the images, or is this still a theoretical risk?

**Comment by hwarden162** [comment]
They could have but didn't, they were trying to show something else. They looked at perturbation energy (a measure of how much difference the adversarial mask introduced to the data) to show that small perturbations in the input image caused wildly different classifications which suggests that the models could be overfitting. So they were more aiming for showing "overfitting is common in computational pathology and this is a way of measuring it" rather than "this attack could be used on this system". It's a shame but it is still a nice figure that links back to other parts of the course. I'll have another read of the paper and see if they mention any possible malicious implications.

**Comment by tompollard** [comment]
Thanks, it's a nice example, so no worries if you can't find anything. Please could you take a look at the build error? As far as I can see, it has something to do with branch names (possibly a bug unrelated to this pull request...perhaps something needs fixing in our github actions?)

**Comment by tompollard** [comment]
@hwarden162 hopefully the build error was fixed in https://github.com/carpentries-incubator/machine-learning-responsible-python/pull/13. Please could you rebase this pull request on the gh-pages branch?

**Pull request closed without merging**
